name: Nairuby
markdown: redcarpet
highlighter: pygments
permalink: /:categories/:year/:month/:title/
relative_permalinks: false

redcarpet:
  extensions: ['no_intra_emphasis', 'fenced_code_blocks', 'autolink', 'tables']

sass:
  sass_dir: _sass
  style: :compressed

exclude: ['CNAME',
          'Gemfile',
          'Gemfile.lock',
          '*.sublime-project',
          'README.md'
          ]

nairuby:
  github_url: https://github.com/Nairuby
  twitter_url: https://twitter.com/NairubyKE
  facebook_url: https://facebook.com/NairubyKE
  google_plus_url: https://plus.google.com/113027199805523831412/posts
